export const BOOKING_CONTAINER_REQUEST = 'BOOKING_CONTAINER_REQUEST';
export const BOOKING_CONTAINER_SUCCESS = 'BOOKING_CONTAINER_SUCCESS';
export const BOOKING_CONTAINER_FAIL = 'BOOKING_CONTAINER_FAIL';
export const BOOKING_CONTAINER_RESET = 'BOOKING_CONTAINER_RESET';
