export const DASHBOARD_BOOKINGS_REQUEST = 'DASHBOARD_BOOKINGS_REQUEST';
export const DASHBOARD_BOOKINGS_SUCCESS = 'DASHBOARD_BOOKINGS_SUCCESS';
export const DASHBOARD_BOOKINGS_FAIL = 'DASHBOARD_BOOKINGS_FAIL';
export const DASHBOARD_BOOKINGS_RESET = 'DASHBOARD_BOOKINGS_RESET';
