// booking constants
export const DASHBOARD_BOOKING_REQUEST = 'DASHBOARD_BOOKING_REQUEST';
export const DASHBOARD_BOOKING_SUCCESS = 'DASHBOARD_BOOKING_SUCCESS';
export const DASHBOARD_BOOKING_FAIL = 'DASHBOARD_BOOKING_FAIL';
